# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='None', max_length=5000, null=True)),
                ('urls1', models.CharField(blank=True, max_length=512, null=True)),
                ('urls2', models.CharField(blank=True, max_length=512, null=True)),
                ('urls3', models.CharField(blank=True, max_length=512, null=True)),
                ('urls4', models.CharField(blank=True, max_length=512, null=True)),
                ('urls5', models.CharField(blank=True, max_length=512, null=True)),
                ('image', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('backupImage', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('subName', models.CharField(default='None', max_length=128, unique=True)),
                ('pageID', models.CharField(default='None', max_length=64, unique=True)),
            ],
        ),
    ]
