# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleName', models.CharField(max_length=128, unique=True)),
                ('articleDescription', models.TextField(blank=True, default='None', max_length=5000, null=True)),
                ('articleIrl', models.CharField(max_length=128, unique=True)),
                ('articleImage', models.CharField(max_length=128, unique=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Artist')),
            ],
        ),
    ]
