# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='articleIrl',
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(default='None', max_length=128),
        ),
    ]
