# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20161120_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profession',
            field=models.TextField(blank=True, default='None', max_length=5000, null=True),
        ),
    ]
