# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20161123_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='pageID',
        ),
    ]
