# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 21:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_article_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='tweet_added_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 18, 21, 39, 5, 375889, tzinfo=utc), verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='article',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 17, 21, 44, 5, 377048, tzinfo=utc), verbose_name='date added'),
        ),
    ]
